import { useState, useEffect } from 'react';
import {
  Dialog, DialogTitle, DialogContent, DialogActions,
  Button, Box, Typography, CircularProgress
} from '@mui/material';
import { IosShare, ContentCopy, CheckCircleOutline } from '@mui/icons-material';
import api from '../api/axios';
import { format } from 'date-fns';

const STATUS_CONFIG = {
  OPEN:        { label: 'Open' },
  IN_PROGRESS: { label: 'In Progress' },
  BLOCKED:     { label: 'Blocked' },
  ON_HOLD:     { label: 'On Hold' },
  COMPLETED:   { label: 'Completed' },
  CANCELLED:   { label: 'Cancelled' },
};

const STATUS_EMOJI = {
  COMPLETED: '✅', IN_PROGRESS: '🔄', BLOCKED: '🚫',
  ON_HOLD: '⏸️', CANCELLED: '❌', OPEN: '⬜',
};

const buildSubtree = async (id) => {
  const { data: children } = await api.get(`/initiatives?parentId=${id}`);
  const result = [];
  for (const child of children) {
    const node = { ...child, subChildren: [] };
    if (child._count?.children > 0) {
      node.subChildren = await buildSubtree(child.id);
    }
    result.push(node);
  }
  return result;
};

const formatSubtree = (nodes, depth = 0) => {
  if (!nodes.length) return '';
  const indent = '  '.repeat(depth);
  return nodes.map(node => {
    const emoji = STATUS_EMOJI[node.status] || '⬜';
    const due = node.dueDate ? ` · Due ${format(new Date(node.dueDate), 'MMM d, yyyy')}` : '';
    const priority = node.priority && node.priority !== 'MEDIUM' ? ` [${node.priority}]` : '';
    const lines = [`${indent}${emoji} ${node.title}${priority}${due}`];
    if (node.subChildren?.length) {
      lines.push(formatSubtree(node.subChildren, depth + 1));
    }
    return lines.join('\n');
  }).join('\n');
};

export default function InitiativeSummaryDialog({ open, onClose, initiativeId, initiativeData }) {
  const [loading, setLoading] = useState(false);
  const [summaryText, setSummaryText] = useState('');
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    if (!open || !initiativeId) return;
    setLoading(true);
    setCopied(false);
    setSummaryText('');

    const generate = async () => {
      try {
        // Fetch full initiative data if not provided
        const d = initiativeData || (await api.get(`/initiatives/${initiativeId}`)).data;
        const subtree = await buildSubtree(initiativeId);
        const div = '─'.repeat(44);

        const lines = [
          '📋 INITIATIVE SUMMARY',
          div,
          `Title:       ${d.title}`,
          `Type:        ${d.type}`,
          `Status:      ${STATUS_CONFIG[d.status]?.label || d.status}`,
          `Priority:    ${d.priority || '—'}`,
          d.dueDate ? `Due Date:    ${format(new Date(d.dueDate), 'MMMM d, yyyy')}` : null,
          d.assignees?.length ? `Assignees:   ${d.assignees.map(a => a.name).join(', ')}` : null,
          d.tags?.length ? `Tags:        ${d.tags.join(', ')}` : null,
          div,
        ].filter(Boolean);

        if (d.description?.trim()) {
          lines.push('Description:');
          lines.push(d.description.trim());
          lines.push('');
        }

        if (subtree.length) {
          lines.push(div);
          lines.push('SUB-TASKS');
          lines.push(formatSubtree(subtree, 0));
          lines.push('');
        }

        lines.push(div);
        lines.push(`Generated by The Manager · ${format(new Date(), 'MMMM d, yyyy')}`);

        setSummaryText(lines.join('\n'));
      } catch (e) {
        console.error('Failed to generate summary', e);
        setSummaryText('Failed to generate summary. Please try again.');
      } finally {
        setLoading(false);
      }
    };

    generate();
  }, [open, initiativeId]); // eslint-disable-line react-hooks/exhaustive-deps

  const handleCopy = () => {
    navigator.clipboard.writeText(summaryText).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    });
  };

  return (
    <Dialog
      open={open}
      onClose={onClose}
      maxWidth="sm"
      fullWidth
      PaperProps={{ sx: { maxHeight: '80vh', display: 'flex', flexDirection: 'column' } }}
    >
      <DialogTitle sx={{ fontWeight: 700, fontSize: '1rem', display: 'flex', alignItems: 'center', gap: 1, pb: 1, flexShrink: 0 }}>
        <IosShare fontSize="small" sx={{ color: 'primary.main' }} />
        Initiative Summary
      </DialogTitle>
      <DialogContent sx={{ pt: '4px !important', overflowY: 'auto', flex: 1 }}>
        {loading ? (
          <Box display="flex" alignItems="center" justifyContent="center" py={4} gap={1.5}>
            <CircularProgress size={20} />
            <Typography variant="body2" color="text.secondary">Building summary…</Typography>
          </Box>
        ) : (
          <Box
            component="pre"
            sx={{
              fontFamily: 'monospace',
              fontSize: '0.78rem',
              lineHeight: 1.65,
              whiteSpace: 'pre-wrap',
              wordBreak: 'break-word',
              bgcolor: '#f8fafc',
              border: '1px solid #e2e8f0',
              borderRadius: 1.5,
              p: 2,
              m: 0,
            }}
          >
            {summaryText}
          </Box>
        )}
      </DialogContent>
      <DialogActions sx={{ px: 3, pb: 2.5, gap: 1, flexShrink: 0 }}>
        <Button size="small" onClick={onClose} sx={{ color: 'text.secondary' }}>Close</Button>
        <Button
          size="small"
          variant="contained"
          disabled={loading || !summaryText}
          startIcon={copied ? <CheckCircleOutline fontSize="small" /> : <ContentCopy fontSize="small" />}
          onClick={handleCopy}
          sx={{
            bgcolor: copied ? 'success.main' : undefined,
            '&:hover': { bgcolor: copied ? 'success.dark' : undefined },
          }}
        >
          {copied ? 'Copied!' : 'Copy to Clipboard'}
        </Button>
      </DialogActions>
    </Dialog>
  );
}
